# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Prereq-B
version:      0.01
version_from: lib/Acme/Prereq/B.pm
installdirs:  site
requires:
    Acme::Prereq::A:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
